#!/usr/bin/env bash
# AURA Bootstrap Script — First-time setup wizard
# Usage: ./scripts/bootstrap.sh

set -e

AURA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DB_PATH="${AURA_DIR}/data/aura.db"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

banner() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║         AURA — Audio Upstream Refactor Agent               ║${NC}"
    echo -e "${BLUE}║                   Bootstrap Wizard                         ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

step() {
    echo -e "${BLUE}[*]${NC} $1"
}

success() {
    echo -e "${GREEN}[+]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[!]${NC} $1"
}

error() {
    echo -e "${RED}[-]${NC} $1"
}

# ── Check Prerequisites ──
check_prereqs() {
    step "Checking prerequisites..."

    if ! command -v docker &> /dev/null; then
        error "Docker is not installed. Please install Docker first."
        exit 1
    fi

    if ! command -v docker compose &> /dev/null && ! docker-compose --version &> /dev/null; then
        error "Docker Compose is not installed."
        exit 1
    fi

    success "Docker and Docker Compose are available"
}

# ── Environment Configuration ──
setup_env() {
    step "Checking environment configuration..."

    if [ ! -f "${AURA_DIR}/.env" ]; then
        warn ".env file not found. Creating from template..."

        # Prompt for required values
        echo ""
        echo "Please provide the following configuration:"
        echo ""

        read -rp "OpenAI API Key: " openai_key
        read -rp "JWT Secret (min 16 chars, or press enter for random): " jwt_secret
        read -rp "Admin Email [admin@aura.local]: " admin_email
        admin_email=${admin_email:-admin@aura.local}
        read -rsp "Admin Password [admin123]: " admin_password
        echo ""
        admin_password=${admin_password:-admin123}

        # Generate random JWT secret if not provided
        if [ -z "$jwt_secret" ]; then
            jwt_secret=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p | head -c 32)
            warn "Generated random JWT secret"
        fi

        # Write .env file
        cat > "${AURA_DIR}/.env" << EOF
# AURA Platform Configuration
# Generated by bootstrap.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Required ──
OPENAI_API_KEY=${openai_key}
JWT_SECRET=${jwt_secret}

# ── Optional ──
LOG_LEVEL=INFO
TOKEN_BUDGET_DAILY=1000000
MAX_CONCURRENT_AGENTS=50
AGENT_TIMEOUT_SECONDS=300
ADMIN_EMAIL=${admin_email}
ADMIN_PASSWORD=${admin_password}
EOF

        success ".env file created"
    else
        success ".env file exists"
    fi
}

# ── Data Directory ──
setup_data() {
    step "Setting up data directories..."

    mkdir -p "${AURA_DIR}/data"/{backups,agents,tmp,exports,logs}
    mkdir -p "${AURA_DIR}/secrets"
    chmod 700 "${AURA_DIR}/data" "${AURA_DIR}/secrets"
    success "Data directories ready"
}

# ── Build & Start ──
start_services() {
    step "Building and starting services..."
    echo "    This may take a few minutes on first run..."
    echo ""

    cd "${AURA_DIR}"
    docker compose up --build -d

    # Wait for health check
    step "Waiting for services to be ready..."
    local retries=30
    while [ $retries -gt 0 ]; do
        if curl -s http://localhost:8000/health/ready > /dev/null 2>&1; then
            success "All services are healthy!"
            return 0
        fi
        sleep 2
        retries=$((retries - 1))
        echo -n "."
    done
    echo ""

    warn "Services started but health check is not yet passing"
    warn "Run 'make health' in a few seconds to check again"
}

# ── Summary ──
show_summary() {
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║              Bootstrap Complete!                           ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "AURA is running at:"
    echo "  Dashboard: http://localhost:3000"
    echo "  API:       http://localhost:8000"
    echo ""
    echo "Health check: make health"
    echo "View logs:    make logs"
    echo "Stop:         make down"
    echo ""
    echo "Default login:"
    echo "  Email:    $(grep ADMIN_EMAIL "${AURA_DIR}/.env" | cut -d= -f2)"
    echo "  Password: $(grep ADMIN_PASSWORD "${AURA_DIR}/.env" | cut -d= -f2)"
    echo ""
    echo "Next steps:"
    echo "  1. Open http://localhost:3000 in your browser"
    echo "  2. Login with the admin credentials above"
    echo "  3. Navigate to Command Center to view system status"
    echo ""
}

# ── Main ──
main() {
    banner
    check_prereqs
    setup_env
    setup_data
    start_services
    show_summary
}

main "$@"
