-- Pre-seed Engineering Memory with key architectural decisions from Phase 0
-- These records capture the reasoning behind the most important decisions.

-- ── Engineering Decisions ──

INSERT INTO engineering_decisions
(decision_id, title, subsystem, decision_made, reasoning, context,
 constraints, alternatives_considered, rejected_alternatives,
 operational_impact, scalability_impact, determinism_impact,
 observability_impact, security_impact, cost_impact,
 decided_by, reversible, reversal_conditions)
VALUES
('dec-001', 'SQLite over PostgreSQL', 'S3_KnowledgeSystem',
 'Use SQLite with WAL mode as primary database',
 'Team-scale (20 users, ~200 agents). SQLite WAL handles concurrent readers. No ops overhead. Single-file backup.',
 'P0 foundation phase. Need persistence before any other subsystem works. Must be operational within 5 minutes.',
 '["P2 team scale", "single tenant", "5-min bootstrap"]' ,
 '[{"option":"PostgreSQL","reason_rejected":"Overkill for P2; requires separate container, connection pooling, ops expertise"},{"option":"MySQL","reason_rejected":"Unnecessary complexity; no specific need for MySQL features"}]',
 '["PostgreSQL (operational overhead)", "MySQL (unnecessary complexity)"]',
 'Minimal ops: single file, no separate process. Backup is file copy.',
 'Limited to single-node until P3. Read replicas not possible. Write throughput capped by single-writer WAL.',
 'WAL mode ensures atomic transactions for deterministic replay state. Journal file enables crash recovery.',
 'SQLite PRAGMAs expose metrics. No external monitoring needed.',
 'Local file access. No network attack surface for DB. Backup encryption TBD.',
 '$0 licensing. No infrastructure cost.',
 'system', 1,
 'When agent count exceeds 200 OR multi-node deployment needed OR write contention > 50 TPS'
),
('dec-002', 'Docker Compose over Kubernetes', 'S1_Orchestrator',
 'Use Docker Compose for P0-P2 deployment',
 'Single-tenant deployment. Team of 20. Compose provides: service dependencies, health checks, restart policies, dev/prod parity.',
 'P0 foundation. Must deploy in <5 minutes. No K8s expertise assumed on team.',
 '["P2 team scale", "single tenant", "5-min bootstrap"]' ,
 '[{"option":"Kubernetes","reason_rejected":"18+ months away per Constitution Article VII. Massive ops overhead for team scale."},{"option":"Nomad","reason_rejected":"Additional tool to learn. No clear benefit over Compose at this scale."}]',
 '["Kubernetes (18+ months)", "Nomad (unnecessary)"]',
 'Simple: docker compose up. No cluster management. No service mesh.',
 'No horizontal scaling. Single node only. Manual failover.',
 'Deterministic startup order: llm-gateway -> ws-server -> core -> dashboard.',
 'Built-in Docker health checks. Logs via docker compose logs.',
 'Container isolation. No K8s RBAC complexity.',
 '$0. Existing Docker infrastructure.',
 'system', 1,
 'When multi-node deployment needed OR service count exceeds 10 OR automated scaling required'
),
('dec-003', 'In-memory event bus', 'S1_Orchestrator',
 'Use in-memory async pub/sub for P0-P2 events',
 'No external dependencies. Zero deployment complexity. Handles 10K events in ring buffer. Swappable with Redis at P3.',
 'P0 foundation. Event bus must work before any other subsystem. Cannot depend on Redis/RabbitMQ.',
 '["P2 team scale", "no external deps", "hot-swappable"]' ,
 '[{"option":"Redis Streams","reason_rejected":"Requires Redis deployment; P3+ per Constitution Article VII"},{"option":"RabbitMQ","reason_rejected":"Operational complexity; overkill for team scale"},{"option":"NATS","reason_rejected":"Additional infrastructure; not needed at P2"}]',
 '["Redis Streams (P3+)", "RabbitMQ (overkill)", "NATS (unnecessary)"]',
 'No ops. No network partition risk. Zero latency.',
 'Single process only. Events lost on restart. Buffer size 10K max.',
 'Async dispatch never blocks publisher. Ring buffer for replay.',
 'Self-contained. Queue depth exposed as metric.',
 'No network exposure.',
 '$0',
 'system', 1,
 'When event volume exceeds 10K/s OR multi-process architecture needed OR event durability required'
),
('dec-004', 'CLI agents only (never in-process)', 'S2_AgentRuntime',
 'All agents are independent CLI executables communicating via stdin/stdout JSON',
 'Process isolation: OOM in one agent does not crash the core. Language agnostic: agents can be any language. Deterministic: clean process boundaries for replay.',
 'P0 foundation. 14 agent types must run reliably without interfering with each other.',
 '["process isolation", "language agnostic", "deterministic boundaries"]' ,
 '[{"option":"In-process Python classes","reason_rejected":"Memory leak in one agent crashes core. No language flexibility. Tight coupling."},{"option":"gRPC services","reason_rejected":"Additional infrastructure. Overkill for single-node deployment."}]',
 '["In-process classes (coupling)", "gRPC (overkill)"]',
 'OS-level isolation. Clean failure: exit codes 0-5. No shared memory.',
 'Process spawn overhead (~50ms). Per-process memory. Max ~50 concurrent.',
 'Clean boundaries for replay. stdout is the record of truth.',
 'Each agent logs to stdout. Process-level monitoring via psutil.',
 'No shared memory. seccomp-bpf sandbox (P1). Command whitelist.',
 '$0. OS processes.',
 'system', 0,
 'Not reversible without major refactoring. Process model is fundamental.'
),
('dec-005', 'Single LLM provider (OpenAI)', 'S7_LLMCateway',
 'Use OpenAI as sole LLM provider for P0-P2',
 'Single integration path. One API key. One response format. Token budget management simpler.',
 'P0 foundation. LLM gateway must work before agents can function.',
 '["P2 team scale", "token budget", "simplicity"]' ,
 '[{"option":"Multi-provider arbitration","reason_rejected":"P3+ per Constitution. Additional complexity: failover logic, response normalization, cost comparison."},{"option":"Local LLM (Ollama)","reason_rejected":"Hardware requirements (GPU). Slower. Lower quality for complex reasoning."},{"option":"Anthropic Claude","reason_rejected":"Additional API integration. No clear advantage over GPT-4o for this use case."}]',
 '["Multi-provider (P3+)", "Local LLM (hardware)", "Anthropic (no advantage)"]',
 'Single credential to rotate. One SDK version.',
 'No failover if OpenAI is down. Rate limit is hard cap.',
 'Pinned model version (gpt-4o-2024-08-06). Seeded parameters. Deterministic responses.',
 'Single provider metrics. Cache hit rate simple to calculate.',
 'API key in environment variable. No key rotation automation.',
 '~$5-15 per 1M tokens. Budget controlled via daily limit.',
 'system', 1,
 'When OpenAI becomes unavailable OR cost exceeds budget OR multi-model reasoning needed'
),
('dec-006', 'React + Vite dashboard', 'S5_Dashboard',
 'Use React 18 + Vite for the dashboard frontend',
 'Lightweight build tool (fast HMR). No framework lock-in. Component-based architecture. Zustand for state management.',
 'P0 foundation. Dashboard is the primary user interface.',
 '["developer experience", "build speed", "lightweight"]' ,
 '[{"option":"Next.js","reason_rejected":"SSR unnecessary for internal tool. Additional complexity."},{"option":"Angular","reason_rejected":"Heavy framework. Steep learning curve. Overkill for dashboard."},{"option":"Vue.js","reason_rejected":"Good alternative, but team likely more familiar with React ecosystem."}]',
 '["Next.js (unnecessary SSR)", "Angular (too heavy)"]',
 'Vite dev server starts in <1s. Build in ~10s.',
 'Client-side only. No SSR for SEO (not needed).',
 'Deterministic build output. Same bundle every time.',
 'React DevTools integration. Client-side error boundaries.',
 'JWT stored in memory. No SSR token leakage risk.',
 '$0. Open source.',
 'system', 1,
 'When SSR needed OR framework becomes unsupported'
);

-- ── Technical Debt ──

INSERT INTO technical_debt
(debt_id, title, description, subsystem, debt_type,
 interest_rate, current_impact, future_impact,
 estimated_fix_effort, estimated_fix_complexity, payoff_if_fixed, status, severity)
VALUES
('debt-001', 'In-memory event bus loses events on restart',
 'Events published to the in-memory bus are lost when the container restarts. No persistence layer for events.',
 'S1_Orchestrator', 'infrastructure', 'medium',
 'Events lost during restart. Replay may miss events that occurred during restart window.',
 'Incomplete audit trail. Cannot fully reconstruct system state across restarts.',
 '3 days', 'medium',
 'Deterministic event recovery, complete audit trail, reliable replay',
 'open', 'medium'
),
('debt-002', 'Single-node SQLite with no replication',
 'SQLite runs on a single node with no read replicas or write scaling. All services share one database file.',
 'S3_KnowledgeSystem', 'infrastructure', 'medium',
 'Read queries block on writers. Cannot scale reads horizontally.',
 'Will block horizontal scaling in P3. Team size >20 may hit contention.',
 '5 days', 'high',
 'Horizontal read scaling, better performance under load',
 'open', 'medium'
),
('debt-003', 'No circuit breaker on LLM gateway',
 'The LLM gateway does not implement circuit breaker pattern. Failures can cascade.',
 'S7_LLMCateway', 'design', 'high',
 'If OpenAI is slow/down, requests queue up. Timeout after 120s. No fast-fail.',
 'Under load, queued requests consume memory. Potential OOM. Agent timeouts increase.',
 '2 days', 'medium',
 'Fast-fail on LLM outage. Better resource utilization.',
 'open', 'high'
),
('debt-004', 'Basic agent scheduling (no anti-starvation)',
 'The task queue uses simple FIFO. P2 background tasks may starve if P0/P1 queue is always full.',
 'S1_Orchestrator', 'design', 'medium',
 'Background tasks (learning, knowledge base updates) may never run under heavy load.',
 'Knowledge base becomes stale. Learning stops. Long-term quality degrades.',
 '3 days', 'medium',
 'Guaranteed background task execution. Better resource utilization.',
 'open', 'medium'
),
('debt-005', 'Dashboard pages are stubs (P2 full impl)',
 'Only Global Command Center is implemented. Other 11 pages are placeholder components.',
 'S5_Dashboard', 'code', 'low',
 'Users cannot access Migration Center, Knowledge Graph, Agent Observability, etc.',
 'Limited functionality for reviewers and architects. Core workflow only partially supported.',
 '10 days', 'medium',
 'Full dashboard functionality. Complete workflow support.',
 'in_progress', 'low'
),
('debt-006', 'No plugin sandboxing (seccomp-bpf not implemented)',
 'Plugins run without syscall restrictions. A malicious plugin could access the filesystem or network.',
 'S6_Governance', 'infrastructure', 'critical',
 'Plugin can read any file the container can access. No network restrictions.',
 'If plugin is compromised: data exfiltration, lateral movement, system modification.',
 '5 days', 'high',
 'Isolated plugin execution. Reduced attack surface.',
 'open', 'critical'
),
('debt-007', 'No automated backup verification',
 'The backup script creates a gzip but does not verify restore works.',
 'S1_Orchestrator', 'infrastructure', 'medium',
 'Backup may be corrupted. Would not know until restore needed.',
 'Disaster recovery may fail. Data loss possible.',
 '1 day', 'low',
 'Confidence in disaster recovery. Verified backup integrity.',
 'open', 'medium'
);

-- ── Known Risks ──

INSERT INTO known_risks
(risk_id, title, description, probability, impact,
 risk_score, affected_subsystems, affected_users,
 mitigation_plan, contingency_plan, residual_risk,
 monitoring_metric, alert_threshold, status, severity, owner)
VALUES
('risk-001', 'SQLite corruption under concurrent writes',
 'Multiple concurrent writers to SQLite under WAL mode could theoretically corrupt the database file if the process crashes at the wrong moment.',
 'low', 'critical', 'medium',
 '["S3_KnowledgeSystem","S1_Orchestrator"]',
 'All users',
 'WAL mode + busy_timeout + synchronous=NORMAL. Integrity check on startup.',
 'Restore from backup. Re-run migrations.',
 'Low: WAL mode is well-tested. SQLite has strong crash guarantees.',
 'integrity_check result',
 'any failure', 'open', 'medium', 'system'
),
('risk-002', 'LLM API rate limiting or outage',
 'OpenAI may rate-limit requests or experience outages. All agents depend on LLM calls.',
 'medium', 'high', 'high',
 '["S7_LLMCateway","S2_AgentRuntime"]',
 'All agents, all users',
 'Token budget manager. LRU response cache. Retry with exponential backoff.',
 'Queue tasks for retry. Use cached responses where possible. Notify users.',
 'Medium: Cache mitigates for common prompts. Retry handles transient failures.',
 'llm_gateway_error_rate',
 '> 10% errors in 5min', 'open', 'high', 'system'
),
('risk-003', 'Replay nondeterminism',
 'LLM responses may vary even with same seed and model version. Async scheduling may produce different event order.',
 'medium', 'high', 'high',
 '["S2_AgentRuntime","S3_KnowledgeSystem"]',
 'Developers reviewing replay',
 'Seeded RNG. Pinned model version. Deterministic sort. Task recorder captures all inputs.',
 'Flag as PARTIAL fidelity. Show divergence points. Human review required.',
 'Medium: Most replays will match. Edge cases flagged for review.',
 'replay_fidelity_mismatch_count',
 'any mismatch', 'open', 'high', 'system'
),
('risk-004', 'Plugin sandbox escape',
 'A malicious or compromised plugin could execute arbitrary code in the container.',
 'low', 'critical', 'medium',
 '["S8_ValidationEngine","S6_Governance"]',
 'All users, all data',
 'Plugin trust levels (BUILTIN only at P2). Code review for plugins.',
 'Container restart. Isolate compromised plugin. Audit all plugin actions.',
 'Medium: P2 only uses BUILTIN plugins. External plugins P3+ with sandbox.',
 'plugin_execution_anomaly_count',
 'any unauthorized syscall', 'open', 'medium', 'system'
),
('risk-005', 'JWT secret compromise',
 'If JWT_SECRET is leaked, attackers can forge authentication tokens.',
 'low', 'critical', 'medium',
 '["S6_Governance","S1_Orchestrator"]',
 'All users',
 'JWT secret must be 32+ chars random. Environment variable only.',
 'Rotate secret. Invalidate all sessions. Force re-login.',
 'Low: Secret stored in env var, not code. Docker secrets at P3.',
 'unauthorized_access_attempts',
 '> 5 failed in 1min', 'open', 'medium', 'system'
),
('risk-006', 'Docker container crash mid-task',
 'If a container crashes while a task is running, the task state may be lost.',
 'low', 'medium', 'low',
 '["S1_Orchestrator","S2_AgentRuntime"]',
 'Task requester',
 'Health checks detect crash. Restart policy brings container back.',
 'Task times out (300s default). Requester notified. Task can be retried.',
 'Low: Timeout mechanism covers this. No permanent state in agents.',
 'container_restart_count',
 '> 2 in 10min', 'open', 'low', 'system'
);

-- ── Deferred Scalability ──

INSERT INTO deferred_scalability
(item_id, title, description, current_approach, target_approach,
 trigger_condition, trigger_metric, trigger_threshold, current_value,
 estimated_effort, estimated_phase, status, priority, subsystem)
VALUES
('scale-001', 'Redis-backed event bus',
 'Current in-memory bus loses events on restart and cannot scale across nodes.',
 'In-memory async Queue with ring buffer',
 'Redis Streams with consumer groups',
 'Multi-node deployment or event durability required',
 'service_instance_count', '> 1',
 '1', '3 days', 'P3', 'deferred', 'medium', 'S1_Orchestrator'
),
('scale-002', 'PostgreSQL for knowledge base',
 'SQLite cannot support concurrent writes at scale or read replicas.',
 'Single-file SQLite with WAL mode',
 'PostgreSQL with read replicas and connection pooling',
 'Team size >20 OR concurrent agents >100 OR write TPS >50',
 'concurrent_agent_count', '> 50',
 '~10 (current design)', '5 days', 'P3', 'deferred', 'medium', 'S3_KnowledgeSystem'
),
('scale-003', 'Horizontal agent scaling',
 'Agents run as local processes. Cannot distribute across nodes.',
 'Local process spawn via subprocess',
 'Distributed task queue (Celery/RQ) with worker nodes',
 'Agent count >50 OR single-node CPU >80%',
 'max_concurrent_agents', '> 50',
 '50 (configurable)', '7 days', 'P3', 'deferred', 'medium', 'S2_AgentRuntime'
),
('scale-004', 'Multi-provider LLM arbitration',
 'Single provider (OpenAI) has no failover. Rate limits are hard caps.',
 'Single OpenAI integration',
 'Priority-based provider selection (OpenAI, Anthropic, local)',
 'OpenAI outage OR cost exceeds budget OR need for model diversity',
 'llm_cost_daily_usd', '> $50',
 '~$0 (no usage yet)', '3 days', 'P3', 'deferred', 'low', 'S7_LLMCateway'
),
('scale-005', 'Kubernetes deployment',
 'Docker Compose cannot handle rolling updates, auto-scaling, or self-healing.',
 'Docker Compose with restart policies',
 'Kubernetes with HPA, rolling updates, health probes',
 'Service count >10 OR need auto-scaling OR production SLA required',
 'service_count', '> 4',
 '4', '10 days', 'P4', 'deferred', 'low', 'S1_Orchestrator'
);

-- ── Future Migrations ──

INSERT INTO future_migrations
(migration_id, title, description, from_state, to_state,
 trigger_phase, trigger_condition, prerequisites,
 estimated_duration, estimated_team_size, rollback_plan,
 risk_level, risk_factors, status, priority)
VALUES
('mig-001', 'SQLite to PostgreSQL migration',
 'Migrate the knowledge base from SQLite to PostgreSQL for horizontal scaling.',
 'SQLite single-file with WAL mode',
 'PostgreSQL with read replicas and pgBouncer',
 'P3',
 'Agent count exceeds 50 OR team exceeds 20 members OR write TPS exceeds 50',
 '["PostgreSQL cluster provisioned","Data migration script tested","Rollback procedure validated"]',
 '3-5 days', 2,
 'Restore SQLite from backup. Point services back to SQLite.',
 'medium',
 '["Data migration may lose in-flight transactions","Schema differences between SQLite and PG","Foreign key behavior differences"]',
 'deferred', 'medium'
),
('mig-002', 'In-memory to Redis event bus',
 'Replace the in-memory event bus with Redis Streams for durability and cross-node distribution.',
 'In-memory async Queue',
 'Redis Streams with consumer groups and persistence',
 'P3',
 'Multi-node deployment OR requirement for event durability across restarts',
 '["Redis cluster provisioned","Event schema compatibility verified","Consumer group logic implemented"]',
 '2-3 days', 1,
 'Fallback to in-memory mode if Redis unavailable. Buffer events in SQLite.',
 'low',
 '["Redis latency adds ~1ms per event","Redis availability becomes critical dependency"]',
 'deferred', 'medium'
),
('mig-003', 'Docker Compose to Kubernetes',
 'Migrate deployment orchestration from Docker Compose to Kubernetes.',
 'Docker Compose with health checks',
 'Kubernetes with HPA, rolling deployments, service mesh',
 'P4',
 'Service count exceeds 10 OR auto-scaling needed OR production SLA > 99%',
 '["K8s cluster provisioned","Ingress controller configured","Monitoring stack (Prometheus/Grafana) deployed","CI/CD pipeline for K8s manifests"]',
 '2-4 weeks', 3,
 'Keep Docker Compose as fallback. Blue-green deployment.',
 'high',
 '["K8s learning curve for team","Increased operational complexity","Potential config drift between Compose and K8s"]',
 'deferred', 'low'
),
('mig-004', 'Single-provider to multi-provider LLM',
 'Add support for multiple LLM providers with arbitration logic.',
 'OpenAI only',
 'OpenAI + Anthropic + local LLM with priority-based routing',
 'P3',
 'OpenAI becomes unavailable OR cost optimization needed OR model diversity required',
 '["Anthropic API access configured","Response format normalization layer","Cost tracking per provider"]',
 '3-5 days', 1,
 'Hard-code OpenAI as fallback. Disable multi-provider routing.',
 'low',
 '["Different providers have different response quality","Cost comparison logic adds complexity"]',
 'deferred', 'low'
);
